services:

  auth-service:
    build: ./AuthMicroService
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  house-selection:
    build: ./HouseSelectionMicroService
    container_name: house-selection
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
