package com.coinquyteam.gateway.Utility;

public enum StatusGateway {
    TOKEN_GENERATION_SUCCESS,
    TOKEN_GENERATION_FAILED,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    TOKEN_VERIFICATION_SUCCESS,
    TOKEN_VERIFICATION_FAILED,
    INTERNAL_ERROR
}
