package HouseLinking.Utility;

public enum HouseStatus
{
    HOUSE_CREATED,
    HOUSE_NOT_FOUND,
    INVALID_CREDENTIALS,
    HOUSE_ALREADY_EXISTS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    HOUSE_LOGGED_IN,
    HOUSE_NOT_CREATED,
}
